# Generated by Django 3.0.7 on 2020-06-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255)),
                ('password', models.CharField(default=None, max_length=255)),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(default=None, max_length=17)),
                ('login', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('last_activity_date', models.DateTimeField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Guest', max_length=255)),
                ('user_ip', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='Started', max_length=255)),
                ('game_date', models.DateTimeField(auto_now_add=True)),
                ('moves', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('sunks', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('player_field', models.CharField(max_length=255)),
                ('player_field_with_enemy_moves', models.CharField(max_length=255)),
                ('enemy_field', models.CharField(max_length=255)),
                ('enemy_field_with_player_moves', models.CharField(max_length=255)),
                ('messages', models.CharField(max_length=2040)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='sea_battle.User')),
            ],
        ),
    ]
